//! Generate a *simulated* Android→Mac capture corpus for `modem rank`.
//!
//! ```bash
//! cargo run --release -p modem-codec --example gen_sim_corpus -- captures/simulated
//! ./target/release/modem rank captures/simulated
//!
//! # …or at a different symbol rate (second argument, default 50):
//! cargo run --release -p modem-codec --example gen_sim_corpus -- captures/sim-25 25
//! ```
//!
//! These WAVs are synthesised by pushing a generated transmission through
//! `modem_core::channel::android_to_mac`. They are **not** over-the-air
//! recordings, and `modem rank` output derived from them must never be
//! presented as one. They exist so the ranking harness has something to chew on
//! reproducibly, on any machine, without a Pixel and a quiet room.
//!
//! Two transmit modes are emitted per (payload, room), because the `p`
//! pulse-shaping flag is a TX-side setting and so is baked into a recording —
//! see the caveat at the end of `docs/capture-corpus.md`:
//!
//!   * `trunk-tx`  — transmitted with trunk's rectangular symbols. This is what
//!                   an Android device running trunk actually puts in the air,
//!                   so ranking these measures what RX-side changes (`m`, `t`)
//!                   can rescue from an existing recording.
//!   * `shaped-tx` — transmitted with `pulse_shape` enabled, i.e. what the
//!                   phone would emit after shipping remedy #1.

use hound::{SampleFormat, WavSpec, WavWriter};
use modem_codec::tx::Transmitter;
use modem_core::channel::{android_to_mac, AndroidToMac};
use modem_core::fsk::{DspVariants, DEFAULT_SYMBOL_RATE, SAMPLE_RATE};
use modem_core::phy::FskPhy;
use std::fs;
use std::path::PathBuf;

fn payloads() -> Vec<(&'static str, Vec<u8>)> {
    vec![
        ("short", b"hello from the Pixel 8 Pro".to_vec()),
        ("marginal", b"the quick brown fox jumps over the lazy dog 0123456789".to_vec()),
        ("take-seven", b"Android to Mac, audible profile, take seven.".to_vec()),
        ("binary180", (0..180u32).map(|i| (i.wrapping_mul(37) & 0xFF) as u8).collect()),
    ]
}

/// Rooms either side of the failure threshold, so the corpus is not all-pass
/// or all-fail.
fn rooms() -> Vec<(&'static str, f32)> {
    vec![("quiet", 0.10), ("nominal", 0.14), ("live", 0.18)]
}

fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

fn main() -> anyhow::Result<()> {
    let out_dir: PathBuf = std::env::args()
        .nth(1)
        .unwrap_or_else(|| "captures/simulated".into())
        .into();
    let symbol_rate: u32 = match std::env::args().nth(2) {
        Some(s) => s.parse().map_err(|_| anyhow::anyhow!("bad symbol rate {s:?}"))?,
        None => DEFAULT_SYMBOL_RATE,
    };
    fs::create_dir_all(&out_dir)?;

    let spec = WavSpec {
        channels: 1,
        sample_rate: SAMPLE_RATE,
        bits_per_sample: 32,
        sample_format: SampleFormat::Float,
    };

    let mut manifest = String::from(
        "# SIMULATED corpus - generated by `cargo run -p modem-codec --example gen_sim_corpus`.\n\
         # These are NOT over-the-air recordings. See docs/android-smoke-test.md.\n\n",
    );
    let mut count = 0;

    for (tx_name, tx_variants) in [
        ("trunk-tx", DspVariants::BASELINE),
        ("shaped-tx", DspVariants { pulse_shape: true, ..DspVariants::BASELINE }),
    ] {
        for (room_name, reverb_wet) in rooms() {
            for (pl_name, payload) in payloads() {
                let tx = Transmitter::new(FskPhy::audible_at(symbol_rate, tx_variants), false);
                let mut air = vec![0f32; 4800];
                air.extend_from_slice(&tx.encode(&payload));
                let heard = android_to_mac(
                    &air,
                    AndroidToMac { reverb_wet, ..AndroidToMac::PIXEL_8_PRO_AT_30CM },
                    SAMPLE_RATE,
                );

                let file = format!("sim-{symbol_rate}sps-{tx_name}-{room_name}-{pl_name}.wav");
                let mut w = WavWriter::create(out_dir.join(&file), spec)?;
                for s in &heard {
                    w.write_sample(*s)?;
                }
                w.finalize()?;

                manifest.push_str(&format!(
                    "[[capture]]\nfile = \"{file}\"\nexpected_hex = \"{}\"\n\
                     direction = \"sim-android-to-mac/{tx_name}/{room_name}\"\nprofile = \"audible\"\n\
                     symbol_rate = {symbol_rate}\n\n",
                    hex(&payload)
                ));
                count += 1;
            }
        }
    }

    fs::write(out_dir.join("manifest.toml"), manifest)?;
    println!(
        "wrote {count} simulated captures at {symbol_rate} sym/s + manifest.toml to {}",
        out_dir.display()
    );
    Ok(())
}
